title: Generative variational timbre spaces
logo: figures/logo.png
description: Generative timbre spaces with perceptually-regularized variational audio synthesis
google_analytics:
theme: jekyll-theme-minimal
